services:
  postgres:
    image: postgres:17
    container_name: superior_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: superior_db
      POSTGRES_USER: salsa_master
      POSTGRES_PASSWORD: picamasomenos
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
